spring:
  data:
    mongodb:
      host: ${MONGODB_HOSTNAME}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DB_NAME}
      username: ${MONGODB_USER}
      password: ${MONGODB_PASSWORD}

server:
  error:
    include-message: always
    include-binding-errors: always
